DATA_DIR = "data"
FIG_DIR = "figures"
LOGGING_DIR = "logging"
RUN_DIR = "run"
RESTORE_FILENAME = "edm_data"
SETTINGS_FILENAME = "settings.ini"
DATE_FORMAT = "%Y_%m_%d"
DATETIME_FORMAT = f"{DATE_FORMAT}_%H_%M_%S"
